# Generated by Django 3.2.21 on 2023-11-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='last_opened',
            new_name='last_updated',
        ),
    ]
